version: "3"
services:
    # コンテナの名称を設定
    jupyter:
        # 同じフォルダにあるDockerfileをビルドする。
        build: 
            .
        # マウントするフォルダを設定。現在のフォルダをDockerコンテナ上の/tmp/workingに紐づける。
        volumes:
            - $PWD:/kaggle
        # コンテナ内の初期ディレクトリを設定
        working_dir: 
            /kaggle
        # ポートフォワードの設定。手元のポート:コンテナのポート
        ports:
            - 8888:8888
        # コンテナ内のTime zoneを日本時間に設定
        environment:
            - "TZ=Japan"        
        # Dockerコンテナを起動したときに走るコマンド
        #   --ip=0.0.0.0   Jupyter Notebookにコンテナ外からアクセスできるようにするオプション。
        #   --allow-root   ルートでの実行を許可するオプション。Dockerコンテナはデフォルトでルート
        #                  権限で起動するため必要
        #   --no-browser   Jupyter Notebook起動時にブラウザを立ち上げないオプション。
        command:
            jupyter notebook --ip=0.0.0.0 --allow-root --no-browser


